services:
  demo-go-api:
    build:
      context: ./apps/go
    image: forge/demo-go-api:local
    container_name: demo-go-api
    ports:
      - "4201:8080"
    environment:
      PORT: "8080"
      FORGE_SERVICE_NAME: demo-go-api
      FORGE_SERVICE_VERSION: 0.1.0
      FORGE_LOG_LEVEL: info
      FORGE_ENV: development
    stop_grace_period: 10s
    restart: "no"

  demo-kotlin-api:
    build:
      context: ./apps/kotlin
    image: forge/demo-kotlin-api:local
    container_name: demo-kotlin-api
    ports:
      - "4202:8080"
    environment:
      PORT: "8080"
      FORGE_SERVICE_NAME: demo-kotlin-api
      FORGE_SERVICE_VERSION: 0.1.0
      FORGE_LOG_LEVEL: info
      FORGE_ENV: development
    stop_grace_period: 10s
    restart: "no"

  demo-rust-api:
    build:
      context: ./apps/rust
    image: forge/demo-rust-api:local
    container_name: demo-rust-api
    ports:
      - "4203:8080"
    environment:
      PORT: "8080"
      FORGE_SERVICE_NAME: demo-rust-api
      FORGE_SERVICE_VERSION: 0.1.0
      FORGE_LOG_LEVEL: info
      FORGE_ENV: development
    stop_grace_period: 10s
    restart: "no"

  demo-python-api:
    build:
      context: ./apps/python
    image: forge/demo-python-api:local
    container_name: demo-python-api
    ports:
      - "4204:8080"
    environment:
      PORT: "8080"
      FORGE_SERVICE_NAME: demo-python-api
      FORGE_SERVICE_VERSION: 0.1.0
      FORGE_LOG_LEVEL: info
      FORGE_ENV: development
    stop_grace_period: 10s
    restart: "no"

  demo-elixir-api:
    build:
      context: ./apps/elixir
    image: forge/demo-elixir-api:local
    container_name: demo-elixir-api
    ports:
      - "4205:8080"
    environment:
      PORT: "8080"
      FORGE_SERVICE_NAME: demo-elixir-api
      FORGE_SERVICE_VERSION: 0.1.0
      FORGE_LOG_LEVEL: info
      FORGE_ENV: development
      RELEASE_DISTRIBUTION: none
    stop_grace_period: 10s
    restart: "no"
