#!/usr/bin/env bash
# Shared local port map for Forge Platform foundation services.

FORGE_PORT_REGISTRY="${FORGE_PORT_REGISTRY:-5000}"
FORGE_PORT_POSTGRES="${FORGE_PORT_POSTGRES:-5001}"
FORGE_PORT_NATS="${FORGE_PORT_NATS:-5002}"
FORGE_PORT_NATS_MONITOR="${FORGE_PORT_NATS_MONITOR:-5003}"
FORGE_PORT_GRAFANA="${FORGE_PORT_GRAFANA:-3000}"
FORGE_PORT_PROMETHEUS="${FORGE_PORT_PROMETHEUS:-3001}"
FORGE_PORT_TEMPO="${FORGE_PORT_TEMPO:-3002}"
FORGE_PORT_LOKI="${FORGE_PORT_LOKI:-3003}"
FORGE_PORT_OTEL_GRPC="${FORGE_PORT_OTEL_GRPC:-4317}"
FORGE_PORT_OTEL_HTTP="${FORGE_PORT_OTEL_HTTP:-4318}"
FORGE_PORT_OTEL_HEALTH="${FORGE_PORT_OTEL_HEALTH:-13133}"
